### ISSUE TITLE
When follow is used, image should not be mandatory

### ISSUE THREAD

**Issue by apoorvam** [leopardslab/dunner#107]
**Describe the bug**
```
test:
  - follow: build
  - image: golang
    commands:
    - ["go", "test", "./..."]

build:
  - image: golang
...
```
Above dunner task file fails validations saying:

```
Validation failed with following errors:
task 'test': image is a required field
```

**Expected behavior**
When follow is used, task image should be optional.
