### ISSUE TITLE
When Follow task is given, actual task is not executed

### ISSUE THREAD

**Issue by apoorvam** [leopardslab/dunner#109]
**Describe the bug**
```
setup:
    image: golang
    commands:
     ....
build:
  - follow: setup
    image: golang
    commands:
    .....
```

Currently, it runs `setup` task first and not run `build` task at all after that.

**Expected behavior**
This is expected to run `setup` task first. If if fails, it should not continue. If it passes it should continue execution of `build` task.

**Comment by ayushjn20** [comment]
@apoorvam I checked on my local machine using the following as the dunner file
```yaml
build:
  - image: node:10.15.0
    commands:
      - ["printenv"]
    envs:
      - FOO_USER=foo
  - follow: update
    image: node:10.15.0
  - image: node:10.15.0
    command: ["npm", "--version"]
update:
  - image: ubuntu
    command: ['apt', 'update']
```
It works fine.
Note: While writing the feature, I assumed that no command will be passed in the `follow` step. Therefore, the following is not supposed to work.
```yaml
  - follow: update
    image: node:10.15.0
    command: ["node", "--version"]
```
