### ISSUE TITLE
Arguments are not replaced in `dir` and `mounts`

### ISSUE THREAD

**Issue by apoorvam** [leopardslab/dunner#142]
**Describe the bug**
An argument passed from cli is not replaced in `dir` field of dunner task.

**To Reproduce**
```
build:
  - image: golang
    commands:
    - ["pwd"]
    mounts:
    - ".:/$1:w"
    dir: "/$1"
```
* Create a task as above
* Run from cli as `dunner do build demo`
* Here `$1` of `mounts` and `dir` is not replaced with passed value of `demo`
* This creates a new directory called `_1` which is incorrect

**Expected behavior**
It should replace `$1` with `demo`

Dunner version: develop branch
`latest-c735602`
