### ISSUE TITLE
Override mounts, envs from actual task by follow task

### ISSUE THREAD

**Issue by apoorvam** [leopardslab/dunner#150]
After the restructure of Dunner config file as per #146 : 

With follow task, one should be able to override the values of envs and mounts defined in the target task by values given in follow task. 

```
tasks:
    status:
       mounts: 
        - "/var:/var:r"
        envs:
        - NAME=foo
        steps:
            - image: mesosphere/aws-cli
              commands: 
                - [aws, 'elasticbeanstalk describe-events --environment-name $1']
    deploy:
        envs:
            - API_BASE=api.example.com
        steps:
            - image: emeraldsquad/sonar-scanner, 
              commands: 
                - [sonar, scan]
            - follow: status
               mounts: 
               - "/tmp:/tmp:r"
               envs:
               - NAME=bar
```

In above example, deploy task is referring `status` task using `follow` field. So the `mounts` and `envs` defined in follow task should be used during execution of `status` task.

So when `status` task is executed via `deploy` task, 

* Envs should get merged. If key already exists, replace with follow task values. In above example `NAME=bar`.
* For envs, all unique mounts will be considered. 

This feature enables user to set some task specific mounts and envs and in cases to override default values in generic task.
