### ISSUE TITLE
Ability to mount other dirs to the task containers

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/Dunner#40]
Users should be able to mount some directories to the Docker containers. Like, 
```
deploy:
- name: 'node'
  mount:
    - './secrets/.npmrc:~/.npmrc:r'
  command: ['npm', 'install']
- name: 'golang'
  mount:
    - '~/go/src/projectname:~/go/src/projectname:wr'
  command: ['go', 'build']
```

`mount` should be an array of strings, and a string has 3 parts as `host-path:container-path:flags`
flags can be optional
