### ISSUE TITLE
Ability to use a task as a step for another task

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/Dunner#41]
Ability to  refer `status` task from `deploy` task as `@status`.

```
deploy:
- name: 'golang'
  command: ['go', 'install']
- name: 'mesosphere/aws-cli'
  command: ['aws', 'elasticbeanstalk update-application --application-name myapp']
- name: '@status' #This refers to another task and can pass args too
  args: 'prod'
status:
- name: 'mesosphere/aws-cli'
  command: ['aws', 'elasticbeanstalk describe-events --environment-name $1'] 
```
